name: Hello World
on: [push]
jobs:
  Hello-World-Job:
    runs-on:
      - codebuild-github-runner-richardfan1126_codebuild-runner-sandbox-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - run: echo "Hello World!"
